version: "1.0"
info:
  model: int-scaffold
packages:
- name: SIQA_GITTest_1909Project
  gitServerName: rimaSCName
  gitUrl: https://github.com/rimabarman
  gitUsername: rimabarman
  gitBranch: main
services:
- serviceName: project.siqa_gittest_1909.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.operations.actions:DBInsert
  packages:
  - name: SIQA_GITTest_1909Project
    version: "1.0"
- serviceName: project.siqa_gittest_1909.integrations:SIQAAdapterFlow
  packages:
  - name: SIQA_GITTest_1909Project
    version: "1.0"
